# Environment Configuration
visible_threshold: 5.0
n_angle: 60
step_size: 0.1
time_threshold: 700
map_name: map.png
log_file_name: result_onlyexp.log

# RL Configuration
actions: 3
episodes: 10000
hidden_layer1_size: 128
hidden_layer2_size: 32
hidden_layer_size: 64

batch_size: 128
gamma: 0.95
eps_start: 0.99
eps_end: 0.01
eps_decay: 1000
target_update: 10
soft_update_rate: 0.1