# Environment Configuration
visible_threshold: 5.0
n_angle: 60
step_size: 0.2
time_threshold: 1000
map_name: map.png

# RL Configuration
actions: 3
episodes: 3000
hidden_layer1_size: 128
hidden_layer2_size: 32

batch_size: 128
gamma: 0.999
eps_start: 0.9
eps_end: 0.05
eps_decay: 200
target_update: 10